spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1ZhbW8rUVZBOFNySHQySlQKSEl6ODhmK1VWN2JrSUZ1cVgyd2E0T2RCUithaFJBTkNBQVJRNkhBbXlUdzJNVUNrbE9VZ0Z3Y3BMbzR3N0gxeAp4V1Q3ak5Oa0djc3JsUzJtZ3Y4aVFYZjhKaThwWVlTajhNWlZVMVNZUGtOcm5UNmhGOGlUaytLegotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNWakNDQWZ1Z0F3SUJBZ0lRSE9lQnBtWGFaVXMzTEJ3QW9CN2phVEFLQmdncWhrak9QUVFEQWpDQmt6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1UUXdNZ1lEVlFRTERDdHFiM0pwY3kxbwpkWEowWld4QWFtOXlhWE5vZFhKMFpXd3RWR2hwYm10UVlXUXRSVEUwTFVkbGJpMDFNVHN3T1FZRFZRUUREREp0CmEyTmxjblFnYW05eWFYTXRhSFZ5ZEdWc1FHcHZjbWx6YUhWeWRHVnNMVlJvYVc1clVHRmtMVVV4TkMxSFpXNHQKTlRBZUZ3MHlOakEwTVRVd056RTNNamhhRncweU9EQTNNVFV3TnpFM01qaGFNRjh4SnpBbEJnTlZCQW9USG0xcgpZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQmpaWEowYVdacFkyRjBaVEUwTURJR0ExVUVDd3dyYW05eWFYTXRhSFZ5CmRHVnNRR3B2Y21semFIVnlkR1ZzTFZSb2FXNXJVR0ZrTFVVeE5DMUhaVzR0TlRCWk1CTUdCeXFHU000OUFnRUcKQ0NxR1NNNDlBd0VIQTBJQUJGRG9jQ2JKUERZeFFLU1U1U0FYQnlrdWpqRHNmWEhGWlB1TTAyUVp5eXVWTGFhQwoveUpCZC93bUx5bGhoS1B3eGxWVFZKZytRMnVkUHFFWHlKT1Q0ck9qWkRCaU1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFmQmdOVkhTTUVHREFXZ0JUYUVPYmlHYTZWSkFDaWQrbFkKTnVYeisvQTNZakFhQmdOVkhSRUVFekFSZ2c5c2IyTmhiQzR3ZUdSaVpTNWtaWFl3Q2dZSUtvWkl6ajBFQXdJRApTUUF3UmdJaEFQTTdBNFEvYXpjcmFEUGRVZ2ZJOUNVS3pnTWZPTUtGcVRVdWVOUjh6Y0ljQWlFQTVVQXZyWEdFClZUdWFxdkVZckdrcitnbHRJcGh1c2pSbGRhdE1oQUpwSDljPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNhekNDQWhLZ0F3SUJBZ0lSQU9hYUhGR3Qrc2ZIQVZEdnd2WVZyVlF3Q2dZSUtvWkl6ajBFQXdJd2daTXgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURTBNRElHQTFVRUN3d3JhbTl5YVhNdAphSFZ5ZEdWc1FHcHZjbWx6YUhWeWRHVnNMVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROVEU3TURrR0ExVUVBd3d5CmJXdGpaWEowSUdwdmNtbHpMV2gxY25SbGJFQnFiM0pwYzJoMWNuUmxiQzFVYUdsdWExQmhaQzFGTVRRdFIyVnUKTFRVd0hoY05Nall3TkRFMU1EY3hNelV4V2hjTk16WXdOREUxTURjeE16VXhXakNCa3pFZU1Cd0dBMVVFQ2hNVgpiV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJRU5CTVRRd01nWURWUVFMREN0cWIzSnBjeTFvZFhKMFpXeEFhbTl5CmFYTm9kWEowWld3dFZHaHBibXRRWVdRdFJURTBMVWRsYmkwMU1Uc3dPUVlEVlFRRERESnRhMk5sY25RZ2FtOXkKYVhNdGFIVnlkR1ZzUUdwdmNtbHphSFZ5ZEdWc0xWUm9hVzVyVUdGa0xVVXhOQzFIWlc0dE5UQlpNQk1HQnlxRwpTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSFJHbEJkWWxxSTRkT1V2WmU3Yy9nZ1pkZVM0SGJGZWlXTkpzeVptCjFMeExCSStnVmUwT3JiYW1JcU5EajdCTlRiVndkUVdFYlBzc2Z1WEoySUlIdUQralJUQkRNQTRHQTFVZER3RUIKL3dRRUF3SUNCREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJUYUVPYmlHYTZWSkFDaQpkK2xZTnVYeisvQTNZakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJBUzlmNjUvLzZRd1Z5dEhVTDl3VjE3ZlRKCm1neWtFMGttKzJZVzEvNkgvd0lnSDh6Y0MrbTdBbW1iYmJLZERtS1cvUmxjZnRwMVpmQWtaQ1ovdFdvT1labz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  ssl:
    bundle: web
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  # Step 5: End of session cookie configuration